version: "3.9"
services:
  eclipso:
      ports:
      - "53:53/udp"
      environment:
          AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
          AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
          ZONE_DIR: "${ZONE_DIR}"
          AWS_REGION: "${AWS_REGION}"    
      image: "calacode/eclipso-dns:latest"
