# This is a TOML document. Boom.
version = 1.1

[domain]
domain = "phasegrid.net"
created = 2021-05-27T07:32:00Z
modified = 2022-05-27T07:32:00Z
verified = true
active = true
ownerid = 10

[defaults]
ttl = 3600
type = 1
class = 1

[[records]]
domain = "neon.us-west-2."
address = "152.67.248.9"

[[records]]
domain = "neon.us-west-1."
address = "216.218.163.107"

[[records]]
domain = "ilo.neon.us-west-1."
address = "216.218.163.106"

[[records]]
domain = "xeon.us-west-1."
address = "216.218.163.99"

[[records]]
domain = "ilo.xeon.us-west-1."
ttl = 60
address = "216.218.163.98"

[[records]]
domain = "."
type = 2
address = "ns1."

[[records]]
domain = "."
type = 2
address = "ns2."

[[records]]
domain = "."
type = 2
address = "ns3."

[[records]]
domain = "ns1."
ttl = 86400
address = "216.218.163.102"

[[records]]
domain = "ns2."
ttl = 86400
address = "216.218.163.101"

[[records]]
domain = "ns3."
ttl = 86400
address = "155.248.192.183"

[[records]]
domain = "neon.us-west-2."
ttl = 86400
address = "152.67.248.9"

[[records]]
domain = "radon.us-west-1."
address = "216.218.163.104"

[[records]]
domain = "idrac.radon.us-west-1."
address = "216.218.163.100"

[[records]]
domain = "pfsense.radon.us-west-1."
address = "216.218.163.105"

[[records]]
domain = "pfsense.xeon.us-west-1."
address = "216.218.163.103"

#[database]
#server = "192.168.1.1"
#ports = [ 8001, 8001, 8002 ]
#connection_max = 5000
#enabled = true

#[servers]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  #[servers.alpha]
  #ip = "10.0.0.1"
  #dc = "eqdc10"

  #[servers.beta]
  #ip = "10.0.0.2"
  #dc = "eqdc10"

#[clients]
#data = [ ["gamma", "delta"], [1, 2] ] # just an update to make sure parsers support it
#score = 4e-08 # to make sure leading zeroes in exponent parts of floats are supported
